services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    networks:
      - default
  server:
    build:
      context: server
      dockerfile: dockerfile
    image: ganhaum
    entrypoint: ./entrypoint.sh
    depends_on:
      - database
    volumes:
      - ./server:/app
    ports:
      - 8080:8080
    networks:
      - default
networks:
  default:
    driver: host
