services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  server:
    build:
      context: server
      dockerfile: dockerfile
    image: ganhaum
    entrypoint: ./entrypoint.sh
    depends_on:
      - database
    environment:
      - STRIPE_SECRET_KEY=
      - STRIPE_PRICE_ID=
    volumes:
      - ./server:/app
    ports:
      - 8080:8080
  web:
    build:
      context: web
      dockerfile: dockerfile
    image: ganhaum
    entrypoint: ./entrypoint.sh
    depends_on:
      - server
    volumes:
      - ./web:/app
    ports:
      - 3000:3000